CMakeLists.txt
README.md

Only set the third_party directory variables if they're not already set (by the dependee project).

CMakeLists.txt: Make it easier to specify third_party vars.

---

CMakeLists.txt

`nlohmann/json` raises a `size_t` to `int` MSVC warning in a public header that will fail the build if `CPPDAP_WARNINGS_AS_ERRORS` is enabled.
Given that this is not our code, the best we can do is to make an exception for this warning.

CMakeLists.txt: Disable MSVC warning from third_party

---

include/dap/network.h

The onError parameter of Server::start is default initialized with `OnError()`, which is an 'invalid target', not a no-op implementation.
Swap the `onError` with a no-op function in this case to avoid a crash for the default argument case.

net::Server: Fix default onError.

---

include/dap/session.h
src/session.cpp
src/session_test.cpp

1.We need the response typeinfo to deserialize the response type.
Why the testcase didn't find out the bug. Because the testquest type and typeresponse type hase the same field name and same filed type.Their typeinfo is the same ,so it didn't find the bug.
2.add another testcase to test the sessiong::send metho.
3.   "body" field in Response is an optional field. So i change the code.

Fix the bug in Session::send method

---

.vscode/launch.json
clang-format-all.sh
include/dap/serialization.h
include/dap/typeof.h
src/json_serializer.cpp
src/json_serializer.h
src/json_serializer_test.cpp
src/network_test.cpp

And other minor formatting and debug config fixes found along the way

Fixes for serializing empty structs

---

include/dap/optional.h

I'm not convinced that `opt.value() = foo` is a desirable pattern,
and worse still it confuses some compilers about which overload to
use.
Just remove it.

optional: Remove the value() method that returns non-const-ref.

---

CMakeLists.txt
README.md

Avoids having to pull this in as an explicit include directory for projects that depend on cppdap.

CMake: Make the cppdap target's include directory public

---

kokoro/ubuntu/presubmit-docker.sh
kokoro/ubuntu/presubmit.sh

`presubmit.sh` now runs `presubmit-docker.sh` using the new radial docker image which contains various toolchains.
The `/bin/using.sh` bash script exports the `using` bash function which can be called to configure toolchains at specific versions.

Kokoro Ubuntu: Switch to docker image

---

src/socket.cpp

Identified by @kuafuwang.
Fixes #29

Fix `dap::Socket::read()` when `recv()` errors

---

src/content_stream.cpp
src/content_stream_test.cpp

The actual length of data read by `dap::Reader::read()` was not being correctly inspected.
Fixed, added test.
Bug identified by @kuafuwang.
Fixes #27

Fix short reads in ContentReader::buffer()

---

CMakeLists.txt
include/dap/serialization.h
include/dap/typeof.h
src/json_serializer.cpp
src/json_serializer.h
src/json_serializer_test.cpp
src/session.cpp
src/typeinfo_test.cpp

`DAP_IMPLEMENT_STRUCT_TYPEINFO_EXT` and `DAP_STRUCT_TYPEINFO_EXT` are two new flavors of `DAP_IMPLEMENT_STRUCT_TYPEINFO` and `DAP_STRUCT_TYPEINFO` that allow you to derive message types.
This involved a bit of reworking on the serializer interfaces.
Added test.
Issue: #32

Add the ability to derive message types from one another.

---

src/typeof.cpp

Instead of constructing them as static fields.
Slightly less cludgy.
Related issue: #40

TypeOf: Move Move TypeInfos to anon namespace

---

include/dap/dap.h
include/dap/typeinfo.h
include/dap/typeof.h
src/dap_test.cpp
src/typeof.cpp

Can be used to explicitly control when the `TypeInfo` static initializers / destructors are called.
Usually not needed.
Issue: #40

Add dap::initialize() and terminate() functions

---

examples/hello_debugger.cpp
include/dap/types.h
src/session.cpp

`int` may be < 64 bit, and some dap protocols use a 64 bit integer. Change to `int64_t` to be consistent.
Fixes: #45

Change dap::integer backing type to int64_t

---

clang-format-all.sh
kokoro/license-check/presubmit-docker.sh
kokoro/license-check/presubmit.cfg
kokoro/license-check/presubmit.sh
kokoro/macos/presubmit.sh
kokoro/ubuntu/presubmit-docker.sh
kokoro/windows/presubmit.bat
license-checker.cfg

`license-checker` is a tool that verifies each file has contains a permitted license header.
See https://github.com/ben-clayton/license-checker for more information.
Also add missing licenses to presubmit scripts.

Add license checker config and kokoro presubmit

---

include/dap/session.h
src/session.cpp
src/session_test.cpp

bindNoThread in conjunction with OnDataAvailable will provide
users with a choice of thread to process requests on. This is
useful when the user relies on single threaded message loop based
design to avoid locking.

Added bindNoThread

---

src/content_stream.cpp
src/content_stream.h
src/content_stream_test.cpp

When there is partial message in reader, popping out the
characters lead to parse errors on the subsequent attempt
to parse. To avoid this, the last matched characters'
index is stored during parsing and reset on error.

Fix content reader for partial input

---

CMakeLists.txt
include/dap/session.h
include/dap/traits.h
src/session.cpp
src/session_test.cpp
src/traits_test.cpp

Unlike the existing handler overloads, these callbacks can be invoked after the handler has returned.
See also #57

Add Session::registerHandler() overloads that support response callbacks

---

license-checker.cfg

The license classification rules in github.com/google/licensecheck have been updated.

license-checker.cfg: Update rules

---

src/json_serializer_test.cpp
src/nlohmann_json_serializer.cpp
src/rapid_json_serializer.cpp

json serializers: Support 64-bit integers.

---

include/dap/traits.h

A workaround for `TRUE` being a `#define` in Windows headers.
Fixes #62

traits.h: Rename `TRUE` to `TRUE_TY`

---

CMakeLists.txt

CMake installation target has been broken for years.
cppdap is only internally used and tested as a library that is included as a sub-module of another project.
In order for a package to be installable, it really needs a stable ABI / API, which we've made no explicit guarantees about.
cppdap is small enough that it can easily be included in a third_party directory of another project.
Remove the broken, unmaintained installation rules.
Fixes: #54

CMake: Remove installation target

---

include/dap/future.h

In C++11, shared_ptr has an explicit operator bool which
means that a shared_ptr can't be implicitly converted to a bool.
adding an explicit cast is a valid fix to the code.

Fix valid function invoke failed in future class

---

kokoro/ubuntu/presubmit.sh

The VM has been updated to Kokoro 14.04, and now the docker instance requires escalated privileges in order to run some sanitizer builds.

kokoro: Fix ASAN build

---

src/session.cpp

"body" field in "Terminated Event" is an optional field, but if no "body" will return {} in processEvent function.
DAP protocol:
code in session.cpp:

fix bug in processEvent function

---

include/dap/any.h
include/dap/serialization.h
src/any_test.cpp
src/json_serializer_test.cpp
src/nlohmann_json_serializer.cpp
src/rapid_json_serializer.cpp

This PR fixes a few bugs I uncovered while fixing the previous bug:
-  nlohmann_json was serializing empty objects as `null` rather than `{}`.
- `any` did not handle assignment to a nullptr_t value, and threw a SEH exception. This was very difficult to track down as a result, so I had `any` handle it by calling `any.reset()` on assignment to a nullptr value. 
- We would encounter this while serializing/deserializing `RunInTerminalRequestArguments` which allows `null` in `env`, [see the spec here](https://github.com/microsoft/debug-adapter-protocol/blob/main/debugAdapterProtocol.json#L779)
- structs, objects, and arrays embedded inside of another `object` were failing to be serialized and deserialized. I changed it such that when we de/serialize `any`, we handle these too.
- While most of …

Fix `any`, embedded `object`, `array`, and struct serialization

---

CMakeLists.txt

The `CPPDAP_JSON_{NLOHMANN,RAPID}` compile definition is used only in cppdap's implementation sources, and does not need to be defined by dependents including our headers.
Also avoid exposing `nlohmann_json::nlohmann_json` as a public link dependency of our installed package.  It is used only when compiling cppdap.

cmake: Avoid exposing implementation dependencies publicly

---

include/dap/typeof.h
src/io.cpp

Avoid `-Wshadow-uncaptured-local` warnings in `DAP_IMPLEMENT_STRUCT_TYPEINFO`.  Previously, applications using `DAP_IMPLEMENT_STRUCT_TYPEINFO` may see:
<app-file>:<app-line>:1: warning: declaration shadows a local variable [-Wshadow-uncaptured-local]
DAP_IMPLEMENT_STRUCT_TYPEINFO(<app-args>),
^
/.../include/dap/typeof.h:199:3: note: expanded from macro 'DAP_IMPLEMENT_STRUCT_TYPEINFO'
DAP_IMPLEMENT_STRUCT_FIELD_SERIALIZATION(STRUCT, NAME, __VA_ARGS__)       \
^
/.../include/dap/typeof.h:168:51: note: expanded from macro 'DAP_IMPLEMENT_STRUCT_FIELD_SERIALIZATION'
if (!d->field(field.name, [&](Deserializer* d) {                        \
^
<app-file>:<app-line>:1: note: previous declaration is here
/.../include/dap/typeof.h:199:3: note: expanded from macro 'DAP_IMPLEMENT_STRUCT_TYPEINFO' …

Fix compiler warning and error encountered on some platforms

---

include/dap/any.h

Previously, clang-analyzer warned:
/.../any.h:146:5: warning: Called C++ object pointer is null [core.CallAndMessage]
We already have similar assertions elsewhere.

any: Tell clang-analyzer a pointer is not nullptr

---

include/dap/any.h

We use `uint8_t` and `uintptr_t` from this header.

any: Add missing include <stdint.h>

---

include/dap/optional.h

The compiler rejects initialization with `= {}`:
error: chosen constructor is explicit in copy-initialization
Use just `{}` instead.

optional: Fix compilation on XLClang 16.1.0

---

CMakeLists.txt

The [CMake documentation](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html) mandates that `cmake_minimum_required` should be called early in the `CMakeLists.txt` prior to any `project()` command.

build(cmake): use min CMake version prior to project call

---

examples/simple_net_client_server.cpp
include/dap/session.h
src/content_stream.cpp
src/content_stream.h
src/content_stream_test.cpp
src/session.cpp
src/string_buffer.h

Opening this PR per https://issuetracker.google.com/issues/282990958.
The reproduction recipe and more details are available in that issue. I can repost them here if needed.
This definitely might need some tweaks. Happy to make any changes to this approach.
---
This commit reworks `ContentReader::read` to better validate the incoming DAP message, closing the underlying `dap::Reader` in the event of an invalid message.
This fixes an infinite loop when parsing an invalid DAP message. In particular, the infinite loop occurs when a cross-site HTTP request from a browser running on the same host as a cppdap server is sent to the server. As cross-site requests to the localhost can be triggered by untrusted JavaScript, more validation of the DAP messages is required to protect cppdap-based …

Fix infinite loop when parsing invalid DAP message.

---

CMakeLists.txt

This allows taking cmake BUILD_SHARED_LIBS option to decide whether to build a shared or static lib This does not change the default (static)

CMake: Allow to build dynamic lib

---

src/socket.cpp

freeaddrinfo(3) only defined to free one or more addrinfo structures returned by getaddrinfo(3).  Thus, it's undefined behaviour for calling freeaddrinfo(3) on nullptr, some libc only call free(3) on the the passed addrinfo, but other libc assumes the addrinfo is always valid.
Let's be explicit instead of relying on undefined behaviours.
Let's drop one call to freeaddrinfo(3) because the addrinfo there is always nullptr and guard the second.

Do not call freeaddrinfo(3) on nullptr

---

src/session.cpp

The other virtual methods are marked with `override`, so there's no good reason for the destructor to not have this too.

Add missing `override` to `~Impl()`

---

CMakeLists.txt

- Add CPPDAP_USE_EXTERNAL_GTEST_PACKAGE option
- Use `enable_testing()` and `add_test()` so that we can run ctest.
With the `CPPDAP_USE_EXTERNAL_GTEST_PACKAGE` option (ON or OFF), It can successfully build and run the tests.
build log:
<details>
```bash
❯ rm -rf build && cmake . -B build/ -DCPPDAP_USE_EXTERNAL_NLOHMANN_JSON_PACKAGE=ON -DCPPDAP_USE_EXTERNAL_GTEST_P
ACKAGE=ON -DCPPDAP_BUILD_TESTS=ON && cmake --build build/ -j20 && ctest --test-dir build/ -j20
-- The CXX compiler identification is GNU 13.2.1
-- The C compiler identification is GNU 13.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C …
```

CMake: add CPPDAP_USE_EXTERNAL_GTEST_PACKAGE option

---

include/dap/typeof.h

Avoid copy-ctor and dtor to get called.
Found by Clazy (range-loop-reference)

Add reference in range-for for non-trivial type

---

CMakeLists.txt

The argument in the corresponding `if()` was changed in commit ae76a38. CMake emits a warning.
Modern CMake style guides advice on ommitting `endif()` arguments.

cmake: Fix inconsistent endif() argument

---

include/dap/network.h

On `gcc-15` without the include header can't be used as is. I noticed `cmake` build failing as:
dap/network.h:31:39: error: 'uint32_t' has not been declared
31 |                                       uint32_t timeoutMillis = 0);
|                                       ^~~~~~~~
The change adds `uint32_t` declaration via `<stdint.h>`.

include/dap/network.h: add <stdint.h> include for `gcc-15`

---

CMakeLists.txt
kokoro/ubuntu/presubmit-docker.sh
kokoro/windows/presubmit.bat
license-checker.cfg

Update to:
- gcc-13 on linux
- cmake 3.31.2 on linux, windows
- python 3.12 on Windows
Turn off warnings in googletest source.  There are some warnings in it that cause compilation failure when using warnings-as-errors

update bot tooling

---

kokoro/windows/msvc-14.14-x64/cmake/presubmit.cfg
kokoro/windows/presubmit.bat
kokoro/windows/vs2022-amd64/cmake/presubmit.cfg
kokoro/windows/vs2022-x86/cmake/presubmit.cfg

Fix msvc-14.4 x86 config to actually configure Win32.
Use cmake --build to build, instead of hardcoding the path to msbuild

kokoro: Add vs2022 configs

---

clang-format-all.sh

Originally authored by Ben Clayton while employed by Google. Marl is a different project.  Change copyright owner to Google LLC like all the other source files.

Fix copyright owner on clang-format-all.sh
